pretrained_model_path: "stabilityai/stable-diffusion-2-1-base"
checkpoint_dir: "methods/tuneavideo/checkpoints_v2"
output_path: "outputs/tuneavideo-results/test" 


data_path:
video: {}
intervention_type: "explicit"
prompts:
video_length: 24
width: 512
height: 512
num_inference_steps: 50
guidance_scale: 4.5
use_inv_latent: True
num_inv_steps: 50
validation_steps: 100
seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True