    prompt:
    neg_prompt: "ugly, blurry, low res, unrealistic, unaesthetic"
    guidance_scale: 7.5
    video_path:
    pretrained_model_path: "stabilityai/stable-diffusion-2-1-base"
    output_path: "outputs/flatten-results"
    video_length: 8
    old_qk: 0
    height: 512
    width: 512
    sample_steps: 50
    inject_step: 40
    seed: 66
    frame_rate: 1 
    fps: 20
    intervention_type: "explicit"
    data_path: 
    video: {}